### ISSUE TITLE
hcaptcha::Hcaptcha can not be built in wasm/wasix

### ISSUE THREAD

**Issue by Lunarequest** [jerus-org/hcaptcha-rs#588]
I'm currently trying to build a server which uses hcaptcha and a error `future cannot be sent between threads safely` is shown for any struct using the hcaptcha trait. I am using wasix which implements many things required by web servers such as socket2, tokio and libc it would be cool if we could use this lib in the backend!

**Comment by jerusdp** [comment]
@Lunarequest  I am working on a fix for this issue and have solved the compilation problem. Development is in the branch "wasm" and enabled using a features "wasi" (for now). 

I have been struggling with testing, as the code compiles but my test application is not run by wasmer, perhaps you can help with this?

**Comment by jerusdp** [comment]
Released.
